# Generated by Django 3.2.21 on 2023-09-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0002_purchasedetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='AED', max_length=12)),
                ('amount', models.FloatField(blank=True)),
                ('charges_json', models.TextField(blank=True, null=True)),
                ('total_charge', models.FloatField(blank=True, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('last_payment_error_json', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('requires_payment_method', 'requires_payment_method'), ('requires_confirmation', 'requires_confirmation'), ('requires_action', 'requires_action'), ('processing', 'processing'), ('Cancelled', 'Cancelled'), ('succeeded', 'succeeded')], db_index=True, max_length=50)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='administrator.purchasedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
