# Generated by Django 3.2.21 on 2023-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='parchase_user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
