# Generated by Django 3.2.21 on 2023-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentattempt_parchase_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='last_payment_json',
            field=models.TextField(null=True),
        ),
    ]
