# Generated by Django 3.2.21 on 2023-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Team Indicator', 'Team Indicator'), ('Team Workforce Plan Corporate', 'Team Workforce Plan Corporate'), ('Team Cost HR Costing and Accounting department', 'Team Cost HR Costing and Accounting department'), ('Payroll Analytics - Business Services', 'Payroll Analytics - Business Services'), ('Gender analytics - Finance and HR department', 'Gender analytics - Finance and HR department'), ('UTILITY METER - SUPPLY CHAIN', 'UTILITY METER - SUPPLY CHAIN'), ('METRICS METER / SALE CENTRE', 'METRICS METER / SALE CENTRE'), ('Warehouse MAP Retail', 'Warehouse MAP Retail'), ('Logistic Controller', 'Logistic Controller'), ('ODOMETERS: BACK OFFICE', 'ODOMETERS: BACK OFFICE')], max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bundle_name', models.TextField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
