# Generated by Django 3.2.21 on 2023-09-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_bundledetails_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledetails',
            name='is_sub_module',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='moduledetails',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.moduledetails'),
        ),
    ]
