# Generated by Django 3.2.21 on 2023-09-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20230914_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledetails',
            name='is_sub_module',
        ),
        migrations.AddField(
            model_name='moduledetails',
            name='is_submodule',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='FeatureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(blank=True, null=True)),
                ('benifit', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.moduledetails')),
            ],
        ),
    ]
