# Generated by Django 3.2.21 on 2023-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_auto_20230914_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledetails',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
