# Generated by Django 3.2.21 on 2023-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_moduledetails_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundledetails',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
