# Generated by Django 3.2.21 on 2023-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_bundledetails_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundledetails',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
