# Generated by Django 3.2.21 on 2023-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_auto_20230928_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledetails',
            name='module_identifier',
            field=models.IntegerField(default=0),
        ),
    ]
