# Generated by Django 3.2.22 on 2023-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_invitedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedetails',
            name='is_free_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
