# Generated by Django 3.2.21 on 2023-11-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0017_invitedetails_is_free_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_subscription_start_date', models.DateField(blank=True, null=True)),
                ('free_subscription_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('bundle', models.ManyToManyField(blank=True, to='superadmin.BundleDetails')),
                ('module', models.ManyToManyField(blank=True, to='superadmin.ModuleDetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
