# Generated by Django 3.2.21 on 2023-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Placed', 'Placed')], db_index=True, max_length=50),
        ),
    ]
