# Generated by Django 3.2.21 on 2023-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_purchasedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='payment_dates',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='received_amounts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
