# Generated by Django 3.2.21 on 2023-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_userassignedmodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='received_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
