# Generated by Django 3.2.21 on 2023-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_csvlogdetails_uploadedcsvfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvlogdetails',
            name='working_type',
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='working_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
