# Generated by Django 3.2.21 on 2023-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20230922_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='is_report_generated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
