# Generated by Django 3.2.21 on 2023-09-23 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0006_alter_uploadedcsvfiles_is_report_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
