# Generated by Django 3.2.21 on 2023-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_subscriptiondetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlogdetails',
            name='extra_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
