# Generated by Django 3.2.21 on 2023-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20231009_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentweightage',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
