# Generated by Django 3.2.21 on 2023-10-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_rename_indivisual_ach_in_csvlogdetails_individual_ach_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='individual_varriable_pay_wgt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
