# Generated by Django 3.2.21 on 2023-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_uploadedcsvfiles_individual_varriable_pay_wgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlogdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='experience',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='region',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
