# Generated by Django 3.2.21 on 2023-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_usersubscriptiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='is_renewed',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
