# Generated by Django 3.2.21 on 2023-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_purchasedetails_is_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='action_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
