# Generated by Django 3.2.21 on 2023-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_purchasedetails_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='action_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
