# Generated by Django 3.2.21 on 2023-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_alter_csvlogdetails_downtime_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlogdetails',
            name='actual',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='actual_calculated',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='no_of_truck_required',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='per_ton_revenue_loss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='total_required_capacity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='vehicle_utilisation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='average_ton_per_truck',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='max_ton_per_truck',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='no_of_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
