# Generated by Django 3.2.21 on 2023-11-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_auto_20231123_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='delay_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='lead_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
