# Generated by Django 3.2.21 on 2023-11-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_auto_20231123_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='delay_duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='lead_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
