# Generated by Django 3.2.21 on 2023-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_auto_20231210_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='process',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='technology',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
