# Generated by Django 3.2.21 on 2023-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_auto_20231213_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='competeld_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
