# Generated by Django 3.2.21 on 2023-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_uploadedcsvfiles_competeld_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsvfiles',
            name='required_availability',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
