# Generated by Django 3.2.21 on 2023-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_alter_uploadedcsvfiles_required_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedcsvfiles',
            old_name='competeld_days',
            new_name='average_cost_employee',
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='average_cost_per_Call',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='call_handle_process',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='working_days_per_week',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
