# Generated by Django 3.2.21 on 2023-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_auto_20231216_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='average_rate_per_impression',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='online_impression_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
