# Generated by Django 3.2.21 on 2023-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_auto_20231217_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlogdetails',
            name='level_of_automation_possible',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='no_of_man_hours_required',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='no_of_resource_required',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='software',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csvlogdetails',
            name='software_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfiles',
            name='average_pay_per_employee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
