# Generated by Django 3.2.21 on 2023-09-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='take_free_subscription',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
