# Generated by Django 3.2.21 on 2023-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230915_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_free_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
