# Generated by Django 3.2.21 on 2023-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230915_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_paid_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_users',
            field=models.IntegerField(default=5),
        ),
    ]
