# Generated by Django 3.2.21 on 2023-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230916_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='loginotp',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], max_length=50),
        ),
    ]
