# Generated by Django 3.2.21 on 2023-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_carddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='ccv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
