# Generated by Django 3.2.22 on 2023-11-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_invitedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteDetails',
        ),
    ]
