# Generated by Django 3.2.21 on 2023-11-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_userprofile_parchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='parchase_id',
        ),
    ]
